background {
    monitor = *
    path = ~/.config/hypr/wallpaper.png
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor = *
    size = 200, 50
    outline_thickness = 3
    dots_spacing = 5
    dots_size = 8
    outer_color = rgba(0, 0, 0, 0.5)
    inner_color = rgba(255, 255, 255, 0.8)
}
